apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

namePrefix: prod-

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3              # more replicas for production traffic
    target:
      kind: Deployment
      name: gitops-app

images:
  - name: gitops-app
    newName: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/gitops-app
    newTag: prod             
